version: '3.8'

services:
  mlapi:
    build: ./mlAPI
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./mlAPI:/app
    command: >
      sh -c "pip install -r requirements/${ENV:-prod}.txt && uvicorn src.main:app --host 0.0.0.0 --port 8000"

networks:
  app_network:
    driver: bridge
