apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
      - name: mlapi
        image: mlapi_image
        ports:
        - containerPort: 8000  # or whatever your ML API uses
        volumeMounts:
        - mountPath: /app/data
          name: shared-data
      volumes:
      - name: shared-data
        hostPath:
          path: /mnt/data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mlapi-service
spec:
  selector:
    app: mlapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000  # match containerPort above
